name: Test Suite
on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        export KODI_INTERACTIVE=0
        ./tests/run.sh

    - uses: actions/upload-artifact@v2
      with:
        name: report
        path: reports/report.html
